"""Central configuration for Raiden Shadow.

All tunable gameplay numbers, enemy specs, wave/level layout, the
weapon/power system table, and the user-settings schema live here
(split one-topic-per-module; this package re-exports the flat
``import config as C`` surface). Nothing imports pygame.
"""
from __future__ import annotations

from .app_info import APP_AUTHOR, APP_NAME, APP_SLUG, VERSION
from .boss_attack import BossAttack
from .boss_behaviours import BOSS_HABITS, DEFAULT_HABIT, habit_for
from .boss_habit import BossHabit
from .enemy_kind import EnemyKind
from .enemy_spec import EnemySpec
from .enemy_stats import (
    ENEMY_BULLET_R,
    ENEMY_BULLET_SPEED,
    ENEMY_SPECS,
    FRAG_SPEED,
    FRAG_SPREAD_DEG,
    MAX_BULLETS,
    RAMMER_DRIFT,
    RAMMER_LOCK_TIME,
    RAMMER_RAMP,
    SHARD_SPREAD,
    SHELL_R,
    SHELL_SPEED,
)
from .item_kind import ItemKind
from .item_rules import (
    BENEFICIAL,
    HAZARDS,
    ITEM_COLORS,
    ITEM_DROP_CHANCE,
    ITEM_FALL_SPEED,
    ITEM_SIZE,
    ITEM_STYLE_DEFAULT_COLOR,
    ITEM_WEIGHTS,
    JAMMER_DROP_PENALTY,
    MAX_ITEMS,
    MEDAL_SCORE,
    SHIELD_TIME,
)
from .level_spec import LevelSpec
from .levels import BOSS_BOTTOM, BOSS_ENTRY_Y, BOSS_TOP, FINAL_LEVEL_INDEX, LEVELS, level_speed
from .palette import PALETTE, PALETTE_HC, Palette
from .player import (
    BONUS_LIFE_MAX,
    BONUS_LIFE_THRESHOLD,
    PLAYER_BANK_HARD,
    PLAYER_BANK_SOFT,
    PLAYER_HALF,
    PLAYER_HITBOX_R,
    PLAYER_INVULN,
    PLAYER_SPEED,
    PLAYER_SPRITE_SCALE,
    PLAYER_START_Y,
    START_LIVES,
)
from .reinforcements import (
    ESCORT_CAP_0,
    ESCORT_CAP_MAX,
    ESCORT_CAP_STEP,
    ESCORT_FIRST_WAVE,
    ESCORT_GROUP_0,
    ESCORT_GROUP_MAX,
    ESCORT_GROUP_STEP,
    ESCORT_INTERVAL_0,
    ESCORT_INTERVAL_MIN,
    ESCORT_INTERVAL_STEP,
    ESCORT_SPAWNS,
    escort_cap,
    escort_group,
    escort_interval,
)
from .scores import (
    HIGH_SCORE_TABLE,
    INITIALS_BLANK,
    INITIALS_LEN,
    INITIALS_LETTERS,
    INITIALS_START,
    INITIALS_TYPED,
    sanitize_initials,
)
from .screen import (
    DISPLAY_MODES,
    FIELD_BOTTOM,
    FIELD_H,
    FIELD_LEFT,
    FIELD_RIGHT,
    FIELD_TOP,
    FIELD_W,
    FPS_LIMITS,
    HUD_H,
    LOGICAL_H,
    LOGICAL_W,
    WALL,
    WINDOW_SCALES,
    window_size,
)
from .settings import DEFAULT_SETTINGS, Settings, settings_to_dict, validate_settings
from .sim import COLLIDE_EPS, MAX_CATCHUP_STEPS, MAX_FRAME_DT, MAX_SUBSTEP, SIM_DT, SIM_HZ
from .stage_theme import StageTheme
from .theme_phase import ThemePhase
from .weapons import (
    BOMB_BOSS_DAMAGE,
    BOMB_CLEAR_BULLETS,
    BOMB_DAMAGE,
    BOMB_MAX,
    BOMB_START,
    MISSILE_BASE_LEVEL,
    MISSILE_DMG,
    MISSILE_INTERVAL,
    MISSILE_MAX_LEVEL,
    MISSILE_R,
    MISSILE_SPEED,
    MISSILE_STREAMS,
    PLAYER_BULLET_DMG,
    PLAYER_BULLET_R,
    PLAYER_BULLET_SPEED,
    WEAPON_BASE_LEVEL,
    WEAPON_FIRE_INTERVAL,
    WEAPON_LEVELS,
    WEAPON_MAX_LEVEL,
    WHIP_BEAD_R,
    WHIP_DMG,
    WHIP_HIT_CD,
    WHIP_LEN,
    WHIP_MAX_ANGLE,
    WHIP_POINTS,
    WHIP_SWEEP_HZ,
    WHIP_TIME,
    WHIP_WAVE_AMP,
    WHIP_WAVE_HZ,
)

__all__ = [
    "APP_AUTHOR",
    "APP_NAME",
    "APP_SLUG",
    "BENEFICIAL",
    "BOMB_BOSS_DAMAGE",
    "BOMB_CLEAR_BULLETS",
    "BOMB_DAMAGE",
    "BOMB_MAX",
    "BOMB_START",
    "BONUS_LIFE_MAX",
    "BONUS_LIFE_THRESHOLD",
    "BOSS_BOTTOM",
    "BOSS_ENTRY_Y",
    "BOSS_HABITS",
    "BOSS_TOP",
    "BossAttack",
    "BossHabit",
    "COLLIDE_EPS",
    "DEFAULT_HABIT",
    "DEFAULT_SETTINGS",
    "DISPLAY_MODES",
    "ENEMY_BULLET_R",
    "ENEMY_BULLET_SPEED",
    "ENEMY_SPECS",
    "ESCORT_CAP_0",
    "ESCORT_CAP_MAX",
    "ESCORT_CAP_STEP",
    "ESCORT_FIRST_WAVE",
    "ESCORT_GROUP_0",
    "ESCORT_GROUP_MAX",
    "ESCORT_GROUP_STEP",
    "ESCORT_INTERVAL_0",
    "ESCORT_INTERVAL_MIN",
    "ESCORT_INTERVAL_STEP",
    "ESCORT_SPAWNS",
    "EnemyKind",
    "EnemySpec",
    "FIELD_BOTTOM",
    "FIELD_H",
    "FIELD_LEFT",
    "FIELD_RIGHT",
    "FIELD_TOP",
    "FIELD_W",
    "FINAL_LEVEL_INDEX",
    "FPS_LIMITS",
    "FRAG_SPEED",
    "FRAG_SPREAD_DEG",
    "HAZARDS",
    "HIGH_SCORE_TABLE",
    "HUD_H",
    "INITIALS_BLANK",
    "INITIALS_LETTERS",
    "INITIALS_LEN",
    "INITIALS_START",
    "INITIALS_TYPED",
    "ITEM_COLORS",
    "ITEM_DROP_CHANCE",
    "ITEM_FALL_SPEED",
    "ITEM_SIZE",
    "ITEM_STYLE_DEFAULT_COLOR",
    "ITEM_WEIGHTS",
    "ItemKind",
    "JAMMER_DROP_PENALTY",
    "LEVELS",
    "LOGICAL_H",
    "LOGICAL_W",
    "LevelSpec",
    "MAX_BULLETS",
    "MAX_CATCHUP_STEPS",
    "MAX_FRAME_DT",
    "MAX_ITEMS",
    "MAX_SUBSTEP",
    "MEDAL_SCORE",
    "MISSILE_BASE_LEVEL",
    "MISSILE_DMG",
    "MISSILE_INTERVAL",
    "MISSILE_MAX_LEVEL",
    "MISSILE_R",
    "MISSILE_SPEED",
    "MISSILE_STREAMS",
    "PALETTE",
    "PALETTE_HC",
    "PLAYER_BANK_HARD",
    "PLAYER_BANK_SOFT",
    "PLAYER_BULLET_DMG",
    "PLAYER_BULLET_R",
    "PLAYER_BULLET_SPEED",
    "PLAYER_HALF",
    "PLAYER_HITBOX_R",
    "PLAYER_INVULN",
    "PLAYER_SPEED",
    "PLAYER_SPRITE_SCALE",
    "PLAYER_START_Y",
    "Palette",
    "RAMMER_DRIFT",
    "RAMMER_LOCK_TIME",
    "RAMMER_RAMP",
    "SHARD_SPREAD",
    "SHELL_R",
    "SHELL_SPEED",
    "SHIELD_TIME",
    "SIM_DT",
    "SIM_HZ",
    "START_LIVES",
    "Settings",
    "StageTheme",
    "ThemePhase",
    "VERSION",
    "WALL",
    "WEAPON_BASE_LEVEL",
    "WEAPON_FIRE_INTERVAL",
    "WEAPON_LEVELS",
    "WEAPON_MAX_LEVEL",
    "WHIP_BEAD_R",
    "WHIP_DMG",
    "WHIP_HIT_CD",
    "WHIP_LEN",
    "WHIP_MAX_ANGLE",
    "WHIP_POINTS",
    "WHIP_SWEEP_HZ",
    "WHIP_TIME",
    "WHIP_WAVE_AMP",
    "WHIP_WAVE_HZ",
    "WINDOW_SCALES",
    "escort_cap",
    "escort_group",
    "escort_interval",
    "habit_for",
    "level_speed",
    "sanitize_initials",
    "settings_to_dict",
    "validate_settings",
    "window_size",
]
